In [1]:
import pandas as pd
import pymongo
from nba_api.stats.static import teams

In [2]:
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)
db = client.sportsDB
b_coll = db.nbamatchupdict

In [39]:
b_coll.insert(superdict)

C:\Users\Will\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  """Entry point for launching an IPython kernel.

ObjectId('5c7236809ec56b11466e2647')

In [3]:
df = pd.read_csv('../uscitiesv1.4.csv')
df.head()

C:\Users\Will\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,population_proper,density,source,incorporated,timezone,zips,id
0,Toronto,NaN,ON,Ontario,NaN,NaN,43.761539,-79.411079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Prairie Ridge,Prairie Ridge,WA,Washington,53053.0,Pierce,47.144300,-122.140800,NaN,NaN,1349.8,polygon,False,America/Los_Angeles,98360 98391,1.840038e+09
2,Edison,Edison,WA,Washington,53057.0,Skagit,48.560200,-122.431100,NaN,NaN,127.4,polygon,False,America/Los_Angeles,98232,1.840017e+09
3,Packwood,Packwood,WA,Washington,53041.0,Lewis,46.608500,-121.670200,NaN,NaN,213.9,polygon,False,America/Los_Angeles,98361,1.840025e+09
4,Wautauga Beach,Wautauga Beach,WA,Washington,53035.0,Kitsap,47.586200,-122.548200,NaN,NaN,261.7,point,False,America/Los_Angeles,98366,1.840038e+09

In [4]:
nba_df = pd.read_csv('csv/games regular season.csv')

opponent_list = nba_df['MATCHUP'].str.split(expand=True)
opponent_list = opponent_list[2]



nba_df['OPPONENT'] = opponent_list
nba_df = nba_df.drop(columns='SEASON_ID')
nba_df.head(20)

nba_df = nba_df[['TEAM_NAME', 'MATCHUP', 'LOCATION', 'WL', 'OPPONENT']]
nba_df.head()

       TEAM_NAME      MATCHUP LOCATION WL OPPONENT
0  Atlanta Hawks  ATL vs. HOU     HOME  L      HOU
1  Atlanta Hawks    ATL @ OKC     AWAY  W      OKC
2  Atlanta Hawks  ATL vs. IND     HOME  W      IND
3  Atlanta Hawks  ATL vs. MIA     HOME  L      MIA
4  Atlanta Hawks    ATL @ LAC     AWAY  L      LAC

In [5]:
grouped_df2 = nba_df.groupby(['TEAM_NAME', 'OPPONENT','LOCATION', 'WL'], as_index=False)
winloss = grouped_df2.count()
winloss.to_csv('csv/teamstats.csv')
winloss

               TEAM_NAME OPPONENT LOCATION WL  MATCHUP
0          Atlanta Hawks      BKN     AWAY  L        7
1          Atlanta Hawks      BKN     AWAY  W        6
2          Atlanta Hawks      BKN     HOME  L        5
3          Atlanta Hawks      BKN     HOME  W        6
4          Atlanta Hawks      BOS     AWAY  L        7
5          Atlanta Hawks      BOS     AWAY  W        5
6          Atlanta Hawks      BOS     HOME  L        7
7          Atlanta Hawks      BOS     HOME  W        6
8          Atlanta Hawks      CHA     AWAY  L        9
9          Atlanta Hawks      CHA     AWAY  W        5
10         Atlanta Hawks      CHA     HOME  L        5
11         Atlanta Hawks      CHA     HOME  W        9
12         Atlanta Hawks      CHI     AWAY  L        6
13         Atlanta Hawks      CHI     AWAY  W        5
14         Atlanta Hawks      CHI     HOME  L        6
15         Atlanta Hawks      CHI     HOME  W        6
16         Atlanta Hawks      CLE     AWAY  L        6
17         Atlanta Hawks      CLE     AWAY  W        7
18         Atlanta Hawks      CLE     HOME  L        5
19         Atlanta Hawks      CLE     HOME  W        7
20         Atlanta Hawks      DAL     AWAY  L        2
21         Atlanta Hawks      DAL     AWAY  W        5
22         Atlanta Hawks      DAL     HOME  L        1
23         Atlanta Hawks      DAL     HOME  W        6
24         Atlanta Hawks      DEN     AWAY  L        4
25         Atlanta Hawks      DEN     AWAY  W        3
26         Atlanta Hawks      DEN     HOME  L        1
27         Atlanta Hawks      DEN     HOME  W        6
28         Atlanta Hawks      DET     AWAY  L        6
29         Atlanta Hawks      DET     AWAY  W        6
...                  ...      ...      ... ..      ...
3415  Washington Wizards      ORL     AWAY  W        9
3416  Washington Wizards      ORL     HOME  L        1
3417  Washington Wizards      ORL     HOME  W       12
3418  Washington Wizards      PHI     AWAY  L        8
3419  Washington Wizards      PHI     AWAY  W        5
3420  Washington Wizards      PHI     HOME  L        2
3421  Washington Wizards      PHI     HOME  W       10
3422  Washington Wizards      PHX     AWAY  L        1
3423  Washington Wizards      PHX     AWAY  W        5
3424  Washington Wizards      PHX     HOME  L        3
3425  Washington Wizards      PHX     HOME  W        4
3426  Washington Wizards      POR     AWAY  L        3
3427  Washington Wizards      POR     AWAY  W        4
3428  Washington Wizards      POR     HOME  L        3
3429  Washington Wizards      POR     HOME  W        4
3430  Washington Wizards      SAC     AWAY  L        5
3431  Washington Wizards      SAC     AWAY  W        2
3432  Washington Wizards      SAC     HOME  L        1
3433  Washington Wizards      SAC     HOME  W        5
3434  Washington Wizards      SAS     AWAY  L        7
3435  Washington Wizards      SAS     HOME  L        3
3436  Washington Wizards      SAS     HOME  W        3
3437  Washington Wizards      TOR     AWAY  L        9
3438  Washington Wizards      TOR     AWAY  W        4
3439  Washington Wizards      TOR     HOME  L       11
3440  Washington Wizards      TOR     HOME  W        2
3441  Washington Wizards      UTA     AWAY  L        5
3442  Washington Wizards      UTA     AWAY  W        1
3443  Washington Wizards      UTA     HOME  L        3
3444  Washington Wizards      UTA     HOME  W        3

[3445 rows x 5 columns]

In [6]:
winloss = winloss.loc[winloss['OPPONENT'] != 'NOH']

In [7]:
wllist = winloss['OPPONENT'].unique()
wllist = sorted(wllist)

nlist = winloss['TEAM_NAME'].unique()
nlist = sorted(nlist)
print((nlist))
print(wllist)

wldict = {'ATL': 'Atlanta Hawks', 'BKN': 'Brooklyn Nets', 'BOS': 'Boston Celtics', 'CHA': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls', 'CLE': 'Cleveland Cavaliers', 'DAL': 'Dallas Mavericks', 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons', 'GSW': 'Golden State Warriors', 'HOU': 'Houston Rockets', 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers', 'LAL': 'Los Angeles Lakers', 'MEM': 'Memphis Grizzlies', 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks', 'MIN': 'Minnesota Timberwolves', 'NOP': 'New Orleans Pelicans',
 'NYK': 'New York Knicks', 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic', 'PHI': 'Philadelphia 76ers', 'PHX': 'Phoenix Suns', 'POR': 'Portland Trail Blazers',
 'SAC': 'Sacramento Kings', 'SAS': 'San Antonio Spurs', 'TOR': 'Toronto Raptors', 'UTA': 'Utah Jazz', 'WAS': 'Washington Wizards'}

['Atlanta Hawks', 'Boston Celtics', 'Brooklyn Nets', 'Charlotte Hornets', 'Chicago Bulls', 'Cleveland Cavaliers', 'Dallas Mavericks', 'Denver Nuggets', 'Detroit Pistons', 'Golden State Warriors', 'Houston Rockets', 'Indiana Pacers', 'Los Angeles Clippers', 'Los Angeles Lakers', 'Memphis Grizzlies', 'Miami Heat', 'Milwaukee Bucks', 'Minnesota Timberwolves', 'New Orleans Pelicans', 'New York Knicks', 'Oklahoma City Thunder', 'Orlando Magic', 'Philadelphia 76ers', 'Phoenix Suns', 'Portland Trail Blazers', 'Sacramento Kings', 'San Antonio Spurs', 'Toronto Raptors', 'Utah Jazz', 'Washington Wizards']
['ATL', 'BKN', 'BOS', 'CHA', 'CHI', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHX', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']

In [8]:
teamname = "Atlanta Hawks"
opponent = "BKN"
superdict = {}
regdict = {}
littledict = {}
wins = 0
losses = 0
for index, row in winloss.iterrows():
    
    if row['TEAM_NAME'] == teamname:
        if row['OPPONENT'] == opponent:
            if row['LOCATION'] == 'AWAY':
                if row['WL'] == "W":
                    wins = row['MATCHUP']
                if row['WL'] == 'L':
                    losses = row['MATCHUP']
        if row['OPPONENT'] != opponent:
            littledict['wins'] = wins
            littledict['losses'] = losses
            regdict[wldict[opponent]] = littledict
            opponent = row['OPPONENT']
            wins = 0
            losses = 0
            littledict = {}
            if row['LOCATION'] == 'AWAY':
                if row['WL'] == "W":
                    wins = row['MATCHUP']
                if row['WL'] == 'L':
                    losses = row['MATCHUP']
    elif row['TEAM_NAME'] != teamname:
        littledict['wins'] = wins
        littledict['losses'] = losses
        regdict[wldict[opponent]] = littledict
        superdict[teamname] = regdict
        regdict = {}
        littledict = {}
        wins = 0
        losses = 0
        teamname = row['TEAM_NAME']
        opponent = row['OPPONENT']
        
        if row['WL'] == "W":
            wins = row['MATCHUP']
        if row['WL'] == 'L':
            losses = row['MATCHUP']
littledict['wins'] = wins
littledict['losses'] = losses
regdict[wldict[opponent]] = littledict
superdict[teamname] = regdict

superdict['Charlotte Hornets']

{'Atlanta Hawks': {'wins': 4, 'losses': 6},
 'Brooklyn Nets': {'wins': 5, 'losses': 2},
 'Boston Celtics': {'wins': 2, 'losses': 7},
 'Chicago Bulls': {'wins': 2, 'losses': 6},
 'Cleveland Cavaliers': {'wins': 0, 'losses': 8},
 'Dallas Mavericks': {'wins': 3, 'losses': 2},
 'Denver Nuggets': {'wins': 2, 'losses': 3},
 'Detroit Pistons': {'wins': 3, 'losses': 5},
 'Golden State Warriors': {'wins': 1, 'losses': 3},
 'Houston Rockets': {'wins': 0, 'losses': 4},
 'Indiana Pacers': {'wins': 3, 'losses': 7},
 'Los Angeles Clippers': {'wins': 0, 'losses': 5},
 'Los Angeles Lakers': {'wins': 3, 'losses': 1},
 'Memphis Grizzlies': {'wins': 4, 'losses': 1},
 'Miami Heat': {'wins': 3, 'losses': 6},
 'Milwaukee Bucks': {'wins': 4, 'losses': 4},
 'Minnesota Timberwolves': {'wins': 3, 'losses': 2},
 'New Orleans Pelicans': {'wins': 0, 'losses': 4},
 'New York Knicks': {'wins': 3, 'losses': 6},
 'Oklahoma City Thunder': {'wins': 2, 'losses': 3},
 'Orlando Magic': {'wins': 8, 'losses': 2},
 'Philadelphia 76ers': {'wins': 3, 'losses': 6},
 'Phoenix Suns': {'wins': 3, 'losses': 2},
 'Portland Trail Blazers': {'wins': 0, 'losses': 5},
 'Sacramento Kings': {'wins': 3, 'losses': 2},
 'San Antonio Spurs': {'wins': 1, 'losses': 4},
 'Toronto Raptors': {'wins': 2, 'losses': 7},
 'Utah Jazz': {'wins': 0, 'losses': 4},
 'Washington Wizards': {'wins': 2, 'losses': 7}}

In [9]:
winloss

               TEAM_NAME OPPONENT LOCATION WL  MATCHUP
0          Atlanta Hawks      BKN     AWAY  L        7
1          Atlanta Hawks      BKN     AWAY  W        6
2          Atlanta Hawks      BKN     HOME  L        5
3          Atlanta Hawks      BKN     HOME  W        6
4          Atlanta Hawks      BOS     AWAY  L        7
5          Atlanta Hawks      BOS     AWAY  W        5
6          Atlanta Hawks      BOS     HOME  L        7
7          Atlanta Hawks      BOS     HOME  W        6
8          Atlanta Hawks      CHA     AWAY  L        9
9          Atlanta Hawks      CHA     AWAY  W        5
10         Atlanta Hawks      CHA     HOME  L        5
11         Atlanta Hawks      CHA     HOME  W        9
12         Atlanta Hawks      CHI     AWAY  L        6
13         Atlanta Hawks      CHI     AWAY  W        5
14         Atlanta Hawks      CHI     HOME  L        6
15         Atlanta Hawks      CHI     HOME  W        6
16         Atlanta Hawks      CLE     AWAY  L        6
17         Atlanta Hawks      CLE     AWAY  W        7
18         Atlanta Hawks      CLE     HOME  L        5
19         Atlanta Hawks      CLE     HOME  W        7
20         Atlanta Hawks      DAL     AWAY  L        2
21         Atlanta Hawks      DAL     AWAY  W        5
22         Atlanta Hawks      DAL     HOME  L        1
23         Atlanta Hawks      DAL     HOME  W        6
24         Atlanta Hawks      DEN     AWAY  L        4
25         Atlanta Hawks      DEN     AWAY  W        3
26         Atlanta Hawks      DEN     HOME  L        1
27         Atlanta Hawks      DEN     HOME  W        6
28         Atlanta Hawks      DET     AWAY  L        6
29         Atlanta Hawks      DET     AWAY  W        6
...                  ...      ...      ... ..      ...
3415  Washington Wizards      ORL     AWAY  W        9
3416  Washington Wizards      ORL     HOME  L        1
3417  Washington Wizards      ORL     HOME  W       12
3418  Washington Wizards      PHI     AWAY  L        8
3419  Washington Wizards      PHI     AWAY  W        5
3420  Washington Wizards      PHI     HOME  L        2
3421  Washington Wizards      PHI     HOME  W       10
3422  Washington Wizards      PHX     AWAY  L        1
3423  Washington Wizards      PHX     AWAY  W        5
3424  Washington Wizards      PHX     HOME  L        3
3425  Washington Wizards      PHX     HOME  W        4
3426  Washington Wizards      POR     AWAY  L        3
3427  Washington Wizards      POR     AWAY  W        4
3428  Washington Wizards      POR     HOME  L        3
3429  Washington Wizards      POR     HOME  W        4
3430  Washington Wizards      SAC     AWAY  L        5
3431  Washington Wizards      SAC     AWAY  W        2
3432  Washington Wizards      SAC     HOME  L        1
3433  Washington Wizards      SAC     HOME  W        5
3434  Washington Wizards      SAS     AWAY  L        7
3435  Washington Wizards      SAS     HOME  L        3
3436  Washington Wizards      SAS     HOME  W        3
3437  Washington Wizards      TOR     AWAY  L        9
3438  Washington Wizards      TOR     AWAY  W        4
3439  Washington Wizards      TOR     HOME  L       11
3440  Washington Wizards      TOR     HOME  W        2
3441  Washington Wizards      UTA     AWAY  L        5
3442  Washington Wizards      UTA     AWAY  W        1
3443  Washington Wizards      UTA     HOME  L        3
3444  Washington Wizards      UTA     HOME  W        3

[3380 rows x 5 columns]

In [10]:
wldict = {'ATL': 'Atlanta Hawks', 'BKN': 'Brooklyn Nets', 'BOS': 'Boston Celtics', 'CHA': 'Charlotte Hornets',
 'CHI': 'Chicago Bulls', 'CLE': 'Cleveland Cavaliers', 'DAL': 'Dallas Mavericks', 'DEN': 'Denver Nuggets',
 'DET': 'Detroit Pistons', 'GSW': 'Golden State Warriors', 'HOU': 'Houston Rockets', 'IND': 'Indiana Pacers',
 'LAC': 'Los Angeles Clippers', 'LAL': 'Los Angeles Lakers', 'MEM': 'Memphis Grizzlies', 'MIA': 'Miami Heat',
 'MIL': 'Milwaukee Bucks', 'MIN': 'Minnesota Timberwolves', 'NOP': 'New Orleans Pelicans',
 'NYK': 'New York Knicks', 'OKC': 'Oklahoma City Thunder',
 'ORL': 'Orlando Magic', 'PHI': 'Philadelphia 76ers', 'PHX': 'Phoenix Suns', 'POR': 'Portland Trail Blazers',
 'SAC': 'Sacramento Kings', 'SAS': 'San Antonio Spurs', 'TOR': 'Toronto Raptors', 'UTA': 'Utah Jazz', 'WAS': 'Washington Wizards'}

In [11]:
print(len(nlist))
print(len(wllist))

30
30

In [12]:
city_df = grouped_df2.count()
city_names = city_df['TEAM_NAME'].str.rsplit(n=1)
city_list = []
for city in city_names:
    city_list.append(city[0])
# city_df['CITY'] = city_list
city_names[2250]

city_df['CITY'] = city_list
city_unique = city_df['CITY'].unique()
city_df.loc[city_df['CITY'] == 'Portland Trail', 'CITY'] = 'Portland'
city_df.loc[city_df['CITY'] == 'Portland']

                   TEAM_NAME OPPONENT LOCATION WL  MATCHUP      CITY
2755  Portland Trail Blazers      ATL     AWAY  L        3  Portland
2756  Portland Trail Blazers      ATL     AWAY  W        3  Portland
2757  Portland Trail Blazers      ATL     HOME  L        4  Portland
2758  Portland Trail Blazers      ATL     HOME  W        3  Portland
2759  Portland Trail Blazers      BKN     AWAY  L        2  Portland
2760  Portland Trail Blazers      BKN     AWAY  W        4  Portland
2761  Portland Trail Blazers      BKN     HOME  L        2  Portland
2762  Portland Trail Blazers      BKN     HOME  W        4  Portland
2763  Portland Trail Blazers      BOS     AWAY  L        3  Portland
2764  Portland Trail Blazers      BOS     AWAY  W        3  Portland
2765  Portland Trail Blazers      BOS     HOME  L        3  Portland
2766  Portland Trail Blazers      BOS     HOME  W        4  Portland
2767  Portland Trail Blazers      CHA     AWAY  L        3  Portland
2768  Portland Trail Blazers      CHA     AWAY  W        3  Portland
2769  Portland Trail Blazers      CHA     HOME  W        7  Portland
2770  Portland Trail Blazers      CHI     AWAY  L        1  Portland
2771  Portland Trail Blazers      CHI     AWAY  W        5  Portland
2772  Portland Trail Blazers      CHI     HOME  L        2  Portland
2773  Portland Trail Blazers      CHI     HOME  W        5  Portland
2774  Portland Trail Blazers      CLE     AWAY  L        4  Portland
2775  Portland Trail Blazers      CLE     AWAY  W        2  Portland
2776  Portland Trail Blazers      CLE     HOME  L        1  Portland
2777  Portland Trail Blazers      CLE     HOME  W        6  Portland
2778  Portland Trail Blazers      DAL     AWAY  L        9  Portland
2779  Portland Trail Blazers      DAL     AWAY  W        4  Portland
2780  Portland Trail Blazers      DAL     HOME  L        5  Portland
2781  Portland Trail Blazers      DAL     HOME  W        6  Portland
2782  Portland Trail Blazers      DEN     AWAY  L        7  Portland
2783  Portland Trail Blazers      DEN     AWAY  W        6  Portland
2784  Portland Trail Blazers      DEN     HOME  L        3  Portland
...                      ...      ...      ... ..      ...       ...
2841  Portland Trail Blazers      ORL     HOME  L        1  Portland
2842  Portland Trail Blazers      ORL     HOME  W        6  Portland
2843  Portland Trail Blazers      PHI     AWAY  L        4  Portland
2844  Portland Trail Blazers      PHI     AWAY  W        2  Portland
2845  Portland Trail Blazers      PHI     HOME  L        1  Portland
2846  Portland Trail Blazers      PHI     HOME  W        6  Portland
2847  Portland Trail Blazers      PHX     AWAY  L        6  Portland
2848  Portland Trail Blazers      PHX     AWAY  W        6  Portland
2849  Portland Trail Blazers      PHX     HOME  L        3  Portland
2850  Portland Trail Blazers      PHX     HOME  W        9  Portland
2851  Portland Trail Blazers      SAC     AWAY  L        6  Portland
2852  Portland Trail Blazers      SAC     AWAY  W        7  Portland
2853  Portland Trail Blazers      SAC     HOME  L        1  Portland
2854  Portland Trail Blazers      SAC     HOME  W       10  Portland
2855  Portland Trail Blazers      SAS     AWAY  L        7  Portland
2856  Portland Trail Blazers      SAS     AWAY  W        4  Portland
2857  Portland Trail Blazers      SAS     HOME  L        5  Portland
2858  Portland Trail Blazers      SAS     HOME  W        8  Portland
2859  Portland Trail Blazers      TOR     AWAY  L        4  Portland
2860  Portland Trail Blazers      TOR     AWAY  W        2  Portland
2861  Portland Trail Blazers      TOR     HOME  L        3  Portland
2862  Portland Trail Blazers      TOR     HOME  W        4  Portland
2863  Portland Trail Blazers      UTA     AWAY  L        8  Portland
2864  Portland Trail Blazers      UTA     AWAY  W        6  Portland
2865  Portland Trail Blazers      UTA     HOME  L        4  Portland
2866  Portland Trail Blazers      UTA     HOME  W       10  Portland
2867  Portland Trail Blazers      WAS     AWAY  L        4  Portland
2868  Portland Trail Blazers      WAS     AWAY  W        3  Portland
2869  Portland Trail Blazers      WAS     HOME  L        4  Portland
2870  Portland Trail Blazers      WAS     HOME  W        3  Portland

[116 rows x 6 columns]

In [13]:
team_state_dict = {'Phoenix Suns':'Arizona',
'Golden State Warriors':'California',
'Los Angeles Clippers': 'California',
'Los Angeles Lakers': 'California',
'Sacramento Kings': 'California',
'Denver Nuggets': 'Colorado',
'Miami Heat': 'Florida',
'Orlando Magic': 'Florida', 
'Atlanta Hawks': 'Georgia',
'Chicago Bulls': 'Illinois',
'Indiana Pacers': 'Indiana',
'New Orleans Pelicans': 'Louisiana',
'Boston Celtics': 'Massachusetts',
'Detroit Pistons': 'Michigan',
'Minnesota Timberwolves': 'Minnesota',
'Brooklyn Nets': 'New York',
'New York Knicks': 'New York',
'Charlotte Hornets': 'North Carolina',
'Cleveland Cavaliers': 'Ohio',
'Oklahoma City Thunder': 'Oklahoma',
'Portland Trail Blazers': 'Oregon',
'Philadelphia 76ers': 'Pennsylvania', 
'Memphis Grizzlies': 'Tennessee',
'Dallas Mavericks': 'Texas',
'Houston Rockets': 'Texas',
'San Antonio Spurs': 'Texas',
'Milwaukee Bucks': 'Wisconsin',
'Utah Jazz': 'Utah',
'Toronto Raptors': 'Ontario',
'Washington Wizards': 'District of Columbia'}

In [20]:
team_state_dict['Phoenix Suns']
st = []
for index, row in city_df.iterrows():
    st.append(team_state_dict[row['TEAM_NAME']])

city_df['STATE'] = st
city_df

,TEAM_NAME,OPPONENT,LOCATION,WL,MATCHUP,CITY,STATE,CITY AND STATE
0,Atlanta Hawks,BKN,AWAY,L,7,Atlanta,Georgia,"Atlanta,Georgia"
1,Atlanta Hawks,BKN,AWAY,W,6,Atlanta,Georgia,"Atlanta,Georgia"
2,Atlanta Hawks,BKN,HOME,L,5,Atlanta,Georgia,"Atlanta,Georgia"
3,Atlanta Hawks,BKN,HOME,W,6,Atlanta,Georgia,"Atlanta,Georgia"
4,Atlanta Hawks,BOS,AWAY,L,7,Atlanta,Georgia,"Atlanta,Georgia"
5,Atlanta Hawks,BOS,AWAY,W,5,Atlanta,Georgia,"Atlanta,Georgia"
6,Atlanta Hawks,BOS,HOME,L,7,Atlanta,Georgia,"Atlanta,Georgia"
7,Atlanta Hawks,BOS,HOME,W,6,Atlanta,Georgia,"Atlanta,Georgia"
8,Atlanta Hawks,CHA,AWAY,L,9,Atlanta,Georgia,"Atlanta,Georgia"
9,Atlanta Hawks,CHA,AWAY,W,5,Atlanta,Georgia,"Atlanta,Georgia"
10,Atlanta Hawks,CHA,HOME,L,5,Atlanta,Georgia,"Atlanta,Georgia"
11,Atlanta Hawks,CHA,HOME,W,9,Atlanta,Georgia,"Atlanta,Georgia"
12,Atlanta Hawks,CHI,AWAY,L,6,Atlanta,Georgia,"Atlanta,Georgia"
13,Atlanta Hawks,CHI,AWAY,W,5,Atlanta,Georgia,"Atlanta,Georgia"
14,Atlanta Hawks,CHI,HOME,L,6,Atlanta,Georgia,"Atlanta,Georgia"
15,Atlanta Hawks,CHI,HOME,W,6,Atlanta,Georgia,"Atlanta,Georgia"
16,Atlanta Hawks,CLE,AWAY,L,6,Atlanta,Georgia,"Atlanta,Georgia"
17,Atlanta Hawks,CLE,AWAY,W,7,Atlanta,Georgia,"Atlanta,Georgia"
18,Atlanta Hawks,CLE,HOME,L,5,Atlanta,Georgia,"Atlanta,Georgia"
19,Atlanta Hawks,CLE,HOME,W,7,Atlanta,Georgia,"Atlanta,Georgia"
20,Atlanta Hawks,DAL,AWAY,L,2,Atlanta,Georgia,"Atlanta,Georgia"
21,Atlanta Hawks,DAL,AWAY,W,5,Atlanta,Georgia,"Atlanta,Georgia"
22,Atlanta Hawks,DAL,HOME,L,1,Atlanta,Georgia,"Atlanta,Georgia"
23,Atlanta Hawks,DAL,HOME,W,6,Atlanta,Georgia,"Atlanta,Georgia"
24,Atlanta Hawks,DEN,AWAY,L,4,Atlanta,Georgia,"Atlanta,Georgia"
25,Atlanta Hawks,DEN,AWAY,W,3,Atlanta,Georgia,"Atlanta,Georgia"
26,Atlanta Hawks,DEN,HOME,L,1,Atlanta,Georgia,"Atlanta,Georgia"
27,Atlanta Hawks,DEN,HOME,W,6,Atlanta,Georgia,"Atlanta,Georgia"
28,Atlanta Hawks,DET,AWAY,L,6,Atlanta,Georgia,"Atlanta,Georgia"
29,Atlanta Hawks,DET,AWAY,W,6,Atlanta,Georgia,"Atlanta,Georgia"
...,...,...,...,...,...,...,...,...
3415,Washington Wizards,ORL,AWAY,W,9,Washington,District of Columbia,"Washington,District of Columbia"
3416,Washington Wizards,ORL,HOME,L,1,Washington,District of Columbia,"Washington,District of Columbia"
3417,Washington Wizards,ORL,HOME,W,12,Washington,District of Columbia,"Washington,District of Columbia"
3418,Washington Wizards,PHI,AWAY,L,8,Washington,District of Columbia,"Washington,District of Columbia"
3419,Washington Wizards,PHI,AWAY,W,5,Washington,District of Columbia,"Washington,District of Columbia"
3420,Washington Wizards,PHI,HOME,L,2,Washington,District of Columbia,"Washington,District of Columbia"
3421,Washington Wizards,PHI,HOME,W,10,Washington,District of Columbia,"Washington,District of Columbia"
3422,Washington Wizards,PHX,AWAY,L,1,Washington,District of Columbia,"Washington,District of Columbia"
3423,Washington Wizards,PHX,AWAY,W,5,Washington,District of Columbia,"Washington,District of Columbia"
3424,Washington Wizards,PHX,HOME,L,3,Washington,District of Columbia,"Washington,District of Columbia"
3425,Washington Wizards,PHX,HOME,W,4,Washington,District of Columbia,"Washington,District of Columbia"
3426,Washington Wizards,POR,AWAY,L,3,Washington,District of Columbia,"Washington,District of Columbia"
3427,Washington Wizards,POR,AWAY,W,4,Washington,District of Columbia,"Washington,District of Columbia"
3428,Washington Wizards,POR,HOME,L,3,Washington,District of Columbia,"Washington,District of Columbia"
3429,Washington Wizards,POR,HOME,W,4,Washington,District of Columbia,"Washington,District of Columbia"
3430,Washington Wizards,SAC,AWAY,L,5,Washington,District of Columbia,"Washington,District of Columbia"
3431,Washington Wizards,SAC,AWAY,W,2,Washington,District of Columbia,"Washington,District of Columbia"
3432,Washington Wizards,SAC,HOME,L,1,Washington,District of Columbia,"Washington,District of Columbia"
3433,Washington Wizards,SAC,HOME,W,5,Washington,District of Columbia,"Washington,District of Columbia"
3434,Washington Wizards,SAS,AWAY,L,7,Washington,District of Columbia,"Washington,District of Columbia"
3435,Washington Wizards,SAS,HOME,L,3,Washington,District of Columbia,"Washington,District of Columbia"
3436,Washington Wizards,SAS,HOME,W,3,Washington,District of Columbia,"Washington,District of Columbia"
3437,Washington Wizards,TOR,AWAY,L,9,Washington,District of Columbia,"Washington,District of Columbia"
3438,Washington Wizards,TOR,AWAY,W,4,Washington,District of Columbia,"Washington,District of Columbia"
3439,Washington Wizards,TOR,HOME,L,11,Washington,District of Columbia,"Washington,District of Columbia"
3440,Washington Wizards,TOR,HOME,W,2,Washington,District of Columbia,"Washington,District of Columbia"
3441,Washington Wizards,UTA,AWAY,L,5,Washington,District of Columbia,"Washington,District of Columbia"
3442,Washington Wizards,UTA,AWAY,W,1,Washington,District of Columbia,"Washington,District of Columbia"
3443,Washington Wizards,UTA,HOME,L,3,Washington,District of Columbia,"Washington,District of Columbia"
3444,Washington Wizards,UTA,HOME,W,3,Washington,District of Columbia,"Washington,District of Columbia"

In [19]:
asdf = pd.concat([city_df['CITY'], city_df['STATE']])

city_df['CITY AND STATE'] = city_df['CITY'] +','+ city_df['STATE']
citystate_unique = city_df['CITY AND STATE'].unique()
citystate_unique
state_unique = city_df['STATE'].unique().tolist()
state_unique

['Georgia',
 'Massachusetts',
 'New York',
 'North Carolina',
 'Illinois',
 'Ohio',
 'Texas',
 'Colorado',
 'Michigan',
 'California',
 'Indiana',
 'Tennessee',
 'Florida',
 'Wisconsin',
 'Minnesota',
 'Louisiana',
 'Oklahoma',
 'Pennsylvania',
 'Arizona',
 'Oregon',
 'Ontario',
 'Utah',
 'District of Columbia']

In [16]:
l = []
for thing in citystate_unique:
    c = thing.split(',')[0]
    s = thing.split(',')[1]
    print(c)

    l.append(df.loc[(df['city'] == c) & (df['state_name'] == s)]['city'].values)
print(l)
li = []
for wtf in l:
    try:
        li.append(wtf[0])
    except:
        print('fail')
li

Atlanta
Boston
Brooklyn
Charlotte
Chicago
Cleveland
Dallas
Denver
Detroit
Golden State
Houston
Indiana
Los Angeles
Memphis
Miami
Milwaukee
Minnesota
New Orleans
New York
Oklahoma City
Orlando
Philadelphia
Phoenix
Portland
Sacramento
San Antonio
Toronto
Utah
Washington
[array(['Atlanta'], dtype=object), array(['Boston'], dtype=object), array(['Brooklyn'], dtype=object), array(['Charlotte'], dtype=object), array(['Chicago'], dtype=object), array(['Cleveland'], dtype=object), array(['Dallas'], dtype=object), array(['Denver'], dtype=object), array(['Detroit'], dtype=object), array([], dtype=object), array(['Houston'], dtype=object), array([], dtype=object), array(['Los Angeles'], dtype=object), array(['Memphis'], dtype=object), array(['Miami'], dtype=object), array(['Milwaukee'], dtype=object), array([], dtype=object), array(['New Orleans'], dtype=object), array(['New York'], dtype=object), array(['Oklahoma City'], dtype=object), array(['Orlando'], dtype=object), array(['Philadelphia'], dtype=object), array(['Phoenix'], dtype=object), array(['Portland'], dtype=object), array(['Sacramento'], dtype=object), array(['San Antonio'], dtype=object), array(['Toronto'], dtype=object), array([], dtype=object), array(['Washington'], dtype=object)]
fail
fail
fail
fail

['Atlanta',
 'Boston',
 'Brooklyn',
 'Charlotte',
 'Chicago',
 'Cleveland',
 'Dallas',
 'Denver',
 'Detroit',
 'Houston',
 'Los Angeles',
 'Memphis',
 'Miami',
 'Milwaukee',
 'New Orleans',
 'New York',
 'Oklahoma City',
 'Orlando',
 'Philadelphia',
 'Phoenix',
 'Portland',
 'Sacramento',
 'San Antonio',
 'Toronto',
 'Washington']

In [24]:
nba_teams = teams.get_teams()
team_list = [team['full_name'] for team in nba_teams]
abbv_list = [team['abbreviation'] for team in nba_teams]
city_list = [team['city'] for team in nba_teams]
state_list = [team['state'] for team in nba_teams]
print(state_list)
d = {'team': team_list, 'abbv': abbv_list, 'city': city_list, 'state': state_list}
team_df = pd.DataFrame(data = d)

#change incorrect state names 


# team_df.to_csv('test.csv')

['Atlanta', 'Massachusetts', 'Ohio', 'Louisiana', 'Illinois', 'Texas', 'Colorado', 'California', 'Texas', 'California', 'California', 'Florida', 'Wisconsin', 'Minnesota', 'New York', 'New York', 'Florida', 'Indiana', 'Pennsylvania', 'Arizona', 'Oregon', 'California', 'Texas', 'Oklahoma', 'Ontario', 'Utah', 'Tennessee', 'District of Columbia', 'Michigan', 'North Carolina']
                      team abbv           city                 state
0            Atlanta Hawks  ATL        Atlanta               Atlanta
1           Boston Celtics  BOS         Boston         Massachusetts
2      Cleveland Cavaliers  CLE      Cleveland                  Ohio
3     New Orleans Pelicans  NOP    New Orleans             Louisiana
4            Chicago Bulls  CHI        Chicago              Illinois
5         Dallas Mavericks  DAL         Dallas                 Texas
6           Denver Nuggets  DEN         Denver              Colorado
7    Golden State Warriors  GSW   Golden State            California
8          Houston Rockets  HOU        Houston                 Texas
9     Los Angeles Clippers  LAC    Los Angeles            California
10      Los Angeles Lakers  LAL    Los Angeles            California
11              Miami Heat  MIA          Miami               Florida
12         Milwaukee Bucks  MIL      Milwaukee             Wisconsin
13  Minnesota Timberwolves  MIN      Minnesota             Minnesota
14           Brooklyn Nets  BKN       Brooklyn              New York
15         New York Knicks  NYK       New York              New York
16           Orlando Magic  ORL        Orlando               Florida
17          Indiana Pacers  IND        Indiana               Indiana
18      Philadelphia 76ers  PHI   Philadelphia          Pennsylvania
19            Phoenix Suns  PHX        Phoenix               Arizona
20  Portland Trail Blazers  POR       Portland                Oregon
21        Sacramento Kings  SAC     Sacramento            California
22       San Antonio Spurs  SAS    San Antonio                 Texas
23   Oklahoma City Thunder  OKC  Oklahoma City              Oklahoma
24         Toronto Raptors  TOR        Toronto               Ontario
25               Utah Jazz  UTA           Utah                  Utah
26       Memphis Grizzlies  MEM        Memphis             Tennessee
27      Washington Wizards  WAS     Washington  District of Columbia
28         Detroit Pistons  DET        Detroit              Michigan
29       Charlotte Hornets  CHA      Charlotte        North Carolina

'Atlanta'

In [26]:
team_df.iloc[0,3] = "Georgia"
team_df.iloc[7,2] = "Oakland"
team_df.iloc[13,2] = "Minneapolis"
team_df.iloc[17,2] = "Indianapolis"
team_df.iloc[25,2] = "Salt Lake City"
team_df

                      team abbv            city                 state
0            Atlanta Hawks  ATL         Atlanta               Georgia
1           Boston Celtics  BOS          Boston         Massachusetts
2      Cleveland Cavaliers  CLE       Cleveland                  Ohio
3     New Orleans Pelicans  NOP     New Orleans             Louisiana
4            Chicago Bulls  CHI         Chicago              Illinois
5         Dallas Mavericks  DAL          Dallas                 Texas
6           Denver Nuggets  DEN          Denver              Colorado
7    Golden State Warriors  GSW         Oakland            California
8          Houston Rockets  HOU         Houston                 Texas
9     Los Angeles Clippers  LAC     Los Angeles            California
10      Los Angeles Lakers  LAL     Los Angeles            California
11              Miami Heat  MIA           Miami               Florida
12         Milwaukee Bucks  MIL       Milwaukee             Wisconsin
13  Minnesota Timberwolves  MIN     Minneapolis             Minnesota
14           Brooklyn Nets  BKN        Brooklyn              New York
15         New York Knicks  NYK        New York              New York
16           Orlando Magic  ORL         Orlando               Florida
17          Indiana Pacers  IND    Indianapolis               Indiana
18      Philadelphia 76ers  PHI    Philadelphia          Pennsylvania
19            Phoenix Suns  PHX         Phoenix               Arizona
20  Portland Trail Blazers  POR        Portland                Oregon
21        Sacramento Kings  SAC      Sacramento            California
22       San Antonio Spurs  SAS     San Antonio                 Texas
23   Oklahoma City Thunder  OKC   Oklahoma City              Oklahoma
24         Toronto Raptors  TOR         Toronto               Ontario
25               Utah Jazz  UTA  Salt Lake City                  Utah
26       Memphis Grizzlies  MEM         Memphis             Tennessee
27      Washington Wizards  WAS      Washington  District of Columbia
28         Detroit Pistons  DET         Detroit              Michigan
29       Charlotte Hornets  CHA       Charlotte        North Carolina

In [27]:
final_team_df = team_df
final_team_df['CITY AND STATE'] = final_team_df['city'] +','+ final_team_df['state']
final_team_df

,team,abbv,city,state,CITY AND STATE
0,Atlanta Hawks,ATL,Atlanta,Georgia,"Atlanta,Georgia"
1,Boston Celtics,BOS,Boston,Massachusetts,"Boston,Massachusetts"
2,Cleveland Cavaliers,CLE,Cleveland,Ohio,"Cleveland,Ohio"
3,New Orleans Pelicans,NOP,New Orleans,Louisiana,"New Orleans,Louisiana"
4,Chicago Bulls,CHI,Chicago,Illinois,"Chicago,Illinois"
5,Dallas Mavericks,DAL,Dallas,Texas,"Dallas,Texas"
6,Denver Nuggets,DEN,Denver,Colorado,"Denver,Colorado"
7,Golden State Warriors,GSW,Oakland,California,"Oakland,California"
8,Houston Rockets,HOU,Houston,Texas,"Houston,Texas"
9,Los Angeles Clippers,LAC,Los Angeles,California,"Los Angeles,California"
10,Los Angeles Lakers,LAL,Los Angeles,California,"Los Angeles,California"
11,Miami Heat,MIA,Miami,Florida,"Miami,Florida"
12,Milwaukee Bucks,MIL,Milwaukee,Wisconsin,"Milwaukee,Wisconsin"
13,Minnesota Timberwolves,MIN,Minneapolis,Minnesota,"Minneapolis,Minnesota"
14,Brooklyn Nets,BKN,Brooklyn,New York,"Brooklyn,New York"
15,New York Knicks,NYK,New York,New York,"New York,New York"
16,Orlando Magic,ORL,Orlando,Florida,"Orlando,Florida"
17,Indiana Pacers,IND,Indianapolis,Indiana,"Indianapolis,Indiana"
18,Philadelphia 76ers,PHI,Philadelphia,Pennsylvania,"Philadelphia,Pennsylvania"
19,Phoenix Suns,PHX,Phoenix,Arizona,"Phoenix,Arizona"
20,Portland Trail Blazers,POR,Portland,Oregon,"Portland,Oregon"
21,Sacramento Kings,SAC,Sacramento,California,"Sacramento,California"
22,San Antonio Spurs,SAS,San Antonio,Texas,"San Antonio,Texas"
23,Oklahoma City Thunder,OKC,Oklahoma City,Oklahoma,"Oklahoma City,Oklahoma"
24,Toronto Raptors,TOR,Toronto,Ontario,"Toronto,Ontario"
25,Utah Jazz,UTA,Salt Lake City,Utah,"Salt Lake City,Utah"
26,Memphis Grizzlies,MEM,Memphis,Tennessee,"Memphis,Tennessee"
27,Washington Wizards,WAS,Washington,District of Columbia,"Washington,District of Columbia"
28,Detroit Pistons,DET,Detroit,Michigan,"Detroit,Michigan"
29,Charlotte Hornets,CHA,Charlotte,North Carolina,"Charlotte,North Carolina"

In [28]:
city_unique = final_team_df['city'].tolist()

state_unique = final_team_df['state'].tolist()
c = []
s = []
lat = []
lng = []
for index, row in final_team_df.iterrows():
        city = row['city']
        state = row['state']
        c.append(df.loc[(df['city'] == city) & (df['state_name'] == state)]['city'].values)
        s.append(df.loc[(df['city'] == city) & (df['state_name'] == state)]['state_name'].values)
        lat.append(df.loc[(df['city'] == city) & (df['state_name'] == state)]['lat'].values)
        lng.append(df.loc[(df['city'] == city) & (df['state_name'] == state)]['lng'].values)
        print((df.loc[(df['city'] == city) & (df['state_name'] == state)]['lat'].values).dtype)
       

#         print('Toronto')
#         c.append(['Toronto'])
#         s.append(['Ontario'])
#         lat.append([[43.761539]])
#         lng.append([-79.411079])

float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64
float64

In [30]:
print(len(c))
print(len(s))
print(len(lat))
d = {"CITY": c, 'STATE': s, 'LAT': lat, 'LNG': lng}
with_coords = pd.DataFrame(data=d)
# z = please['LAT'][0][0]
# z
with_coords

30
30
30

,CITY,STATE,LAT,LNG
0,[Atlanta],[Georgia],[33.7627],[-84.4231]
1,[Boston],[Massachusetts],[42.3189],[-71.0838]
2,[Cleveland],[Ohio],[41.4766],[-81.6805]
3,[New Orleans],[Louisiana],[30.0687],[-89.9288]
4,[Chicago],[Illinois],[41.8373],[-87.6861]
5,[Dallas],[Texas],[32.7938],[-96.7659]
6,[Denver],[Colorado],[39.7621],[-104.8759]
7,[Oakland],[California],[37.7903],[-122.2165]
8,[Houston],[Texas],[29.7871],[-95.3936]
9,[Los Angeles],[California],[34.114000000000004],[-118.4068]
10,[Los Angeles],[California],[34.114000000000004],[-118.4068]
11,[Miami],[Florida],[25.784000000000002],[-80.2102]
12,[Milwaukee],[Wisconsin],[43.06399999999999],[-87.9669]
13,[Minneapolis],[Minnesota],[44.9635],[-93.2679]
14,[Brooklyn],[New York],[40.6501],[-73.9496]
15,[New York],[New York],[40.6943],[-73.9249]
16,[Orlando],[Florida],[28.4801],[-81.3448]
17,[Indianapolis],[Indiana],[39.7771],[-86.1458]
18,[Philadelphia],[Pennsylvania],[40.0076],[-75.134]
19,[Phoenix],[Arizona],[33.5722],[-112.0891]
20,[Portland],[Oregon],[45.5372],[-122.65]
21,[Sacramento],[California],[38.5666],[-121.4683]
22,[San Antonio],[Texas],[29.4722],[-98.5247]
23,[Oklahoma City],[Oklahoma],[35.4677],[-97.5138]
24,[Toronto],[Ontario],[43.761539],[-79.411079]
25,[Salt Lake City],[Utah],[40.7774],[-111.9301]
26,[Memphis],[Tennessee],[35.1047],[-89.9773]
27,[Washington],[District of Columbia],[38.9047],[-77.0163]
28,[Detroit],[Michigan],[42.3834],[-83.1024]
29,[Charlotte],[North Carolina],[35.208],[-80.8308]

In [32]:
z = []
y = []
x = []
w = []
for index, row in with_coords.iterrows():
#     w.append(row['STATE'][0])
#     x.append(row['CITY'][0])
#     y.append(row['LAT'][0])
#     z.append(row['LNG'][0])
    yy = row['LAT'][0]
    xx = row['CITY'][0]
    ww = row['STATE'][0]
    zz = row['LNG'][0]
    
    z.append(zz)
    y.append(yy)
    x.append(xx)
    w.append(ww)

In [35]:
d = {"CITY": x, 'STATE': w, 'LAT': y, 'LNG': z}
please = pd.DataFrame(data=d)

please.to_csv('csv/nba_state_coords.csv')
please

              CITY                 STATE        LAT         LNG
0          Atlanta               Georgia  33.762700  -84.423100
1           Boston         Massachusetts  42.318900  -71.083800
2        Cleveland                  Ohio  41.476600  -81.680500
3      New Orleans             Louisiana  30.068700  -89.928800
4          Chicago              Illinois  41.837300  -87.686100
5           Dallas                 Texas  32.793800  -96.765900
6           Denver              Colorado  39.762100 -104.875900
7          Oakland            California  37.790300 -122.216500
8          Houston                 Texas  29.787100  -95.393600
9      Los Angeles            California  34.114000 -118.406800
10     Los Angeles            California  34.114000 -118.406800
11           Miami               Florida  25.784000  -80.210200
12       Milwaukee             Wisconsin  43.064000  -87.966900
13     Minneapolis             Minnesota  44.963500  -93.267900
14        Brooklyn              New York  40.650100  -73.949600
15        New York              New York  40.694300  -73.924900
16         Orlando               Florida  28.480100  -81.344800
17    Indianapolis               Indiana  39.777100  -86.145800
18    Philadelphia          Pennsylvania  40.007600  -75.134000
19         Phoenix               Arizona  33.572200 -112.089100
20        Portland                Oregon  45.537200 -122.650000
21      Sacramento            California  38.566600 -121.468300
22     San Antonio                 Texas  29.472200  -98.524700
23   Oklahoma City              Oklahoma  35.467700  -97.513800
24         Toronto               Ontario  43.761539  -79.411079
25  Salt Lake City                  Utah  40.777400 -111.930100
26         Memphis             Tennessee  35.104700  -89.977300
27      Washington  District of Columbia  38.904700  -77.016300
28         Detroit              Michigan  42.383400  -83.102400
29       Charlotte        North Carolina  35.208000  -80.830800

In [ ]:
# tname = []
# oppo = []
# loc_away_w = []
# loc_away_l = []
# loc_home_w = []
# loc_home_l = []

# aw = 0
# al = 0
# hw = 0
# hl= 0

# team = " "
# opponent = " "
# location = " "

# for index, row in winloss.iterrows():
    
    
#     if row['TEAM_NAME'] == team:
        
        
#         if row['OPPONENT'] == opponent:
        
            
#             if row['LOCATION'] == "AWAY":
                
#                 if row['WL'] == 'W':
#                     aw +=1
#                     loc_away_w.append(row['MATCHUP'])
#                 elif row['WL'] == 'L':
#                     al +=1
#                     loc_away_l.append(row['MATCHUP'])
                    
#             elif row['LOCATION'] == 'HOME':
                
#                 if row['WL'] == 'W':
#                     hw += 1
#                     loc_home_w.append(row['MATCHUP'])
#                 elif row['WL'] == 'L':
#                     hl += 1
#                     loc_home_l.append(row['MATCHUP'])
                
#         elif row['OPPONENT'] != opponent:
#             tname.append(row['TEAM_NAME'])
#             if aw + al + hw + hl == 0:
#                 print("nodata")
#             elif aw == 0:
#                 loc_away_w.append(0)
#             elif al == 0:
#                 loc_away_l.append(0)
#             elif hw ==0:
#                 loc_home_w.append(0)
#             elif hl == 0:
#                 loc_home_l.append(0)
            
#             aw = 0
#             al = 0
#             hw = 0
#             hl= 0
            
#             opponent = row['OPPONENT']
#             oppo.append(wldict[row['OPPONENT']])

#             if row['LOCATION'] == "AWAY":

#                 if row['WL'] == 'W':
#                     aw +=1
#                     print(row['MATCHUP'])
#                     loc_away_w.append(row['MATCHUP'])
#                 elif row['WL'] == 'L':
#                     al +=1
#                     loc_away_l.append(row['MATCHUP'])

#             elif row['LOCATION'] == 'HOME':

#                 if row['WL'] == 'W':
#                     hw +=1
#                     loc_home_w.append(row['MATCHUP'])
#                 elif row['WL'] == 'L':
#                     hl +=1
#                     loc_home_l.append(row['MATCHUP'])
                    
            
#     elif row['TEAM_NAME'] != team:
#         print(row['TEAM_NAME'])
#         tname.append(row['TEAM_NAME'])
#         team = row['TEAM_NAME']
        
#         opponent = row['OPPONENT']
#         oppo.append(wldict[row['OPPONENT']])
#         if aw + al + hw + hl == 0:
#             print("nodata")
#         elif aw == 0:
#             loc_away_w.append(0)
#         elif al == 0:
#             loc_away_l.append(0)
#         elif hw ==0:
#             loc_home_w.append(0)
#         elif hl == 0:
#             loc_home_l.append(0)

#         aw = 0
#         al = 0
#         hw = 0
#         hl= 0

#         if row['LOCATION'] == "AWAY":

#             if row['WL'] == 'W':
#                 aw +=1
#                 print(row['MATCHUP'])
#                 loc_away_w.append(row['MATCHUP'])
#             elif row['WL'] == 'L':
#                 al +=1
#                 loc_away_l.append(row['MATCHUP'])

#         elif row['LOCATION'] == 'HOME':

#             if row['WL'] == 'W':
#                 hw +=1
#                 loc_home_w.append(row['MATCHUP'])
#             elif row['WL'] == 'L':
#                 hl +=1
#                 loc_home_l.append(row['MATCHUP'])